### ISSUE TITLE
After 2024.1.0 update unavailable devices after one use

### ISSUE THREAD

**Issue by fotis3d** [AlexxIT/SonoffLAN#1301]
After the latest HA update to 2024.1.0 I get all the devices unavailable after I switch them once.

I tried auto/cloud/local with restarts and reloads but it does not fix this.

This happens with all my devices (about 15 Sonoffs) basic, mini, TX switches. Everyone I switch once and then it goes unavailable to HA.

Has anyone experienced the same ?

I switched to 2023.12 and they work fine.

**Comment by jeremysherriff** [comment]
Same issue here - for eWelink GD-W5 garage door relay.
A reload of the integration allows another single activation of the switch.

I will attempt to get debug logs.

**Comment by jeremysherriff** [comment]
@fotis3d it is likely this is resolved with today's release of v3.5.4 ::

- Fix Hass 2024.1 error: RecursionError 1285 1288 1289 1290 1291 1293 1294 1295 1296 1297 

Can you confirm whether this update fixes your issue?

**Comment by devezaam** [comment]
I have the same issue and didn't fix ...

**Comment by fotis3d** [comment]
@jeremysherriff I hadn't even seen there was an update. It seems that works now.

Thanks ;)

**Comment by bluestar888** [comment]
Same issue.No devices get detected whatsoever.Removed itegration ,reinstalled ,no change.
See errro log attached 
[SOnoff_error_log_Jan4.docx](https://github.com/AlexxIT/SonoffLAN/files/13837545/SOnoff_error_log_Jan4.docx)

**Comment by jeremysherriff** [comment]
All Issues resolved for me, but I only have one switch using this integration.

**Comment by mihaitaiosub** [comment]
Same bug for me.I have 14 devices that works with Sonoff integration.My question is if we update the integration to version 3.5.4, will this integration work correctly with core version 2024.1.0? Or with the following core updates?

**Comment by Capcave** [comment]
I am getting this error now even after the 3.5.4 update (and Core 2024.1.0, Supervisor 2023.12.0, Operating System 11.3) both before and after the OS update to 11.3. It works for about 15 mins and then stops. However, I have both ZBBridge and ZBBridgePro on the network and I notice the Pro connected devices are working fine - seems to be limited to the older non Pro devices.

**Comment by mihaitaiosub** [comment]
I don't understand why you mention ZBBridge or ZBBridgePro. These bridges work with the Zigbee network and with Zigbee devices, but we have problems with Sonoff devices connected via Wifi directly to the home router, and further through integration with Home Assistant.

**Comment by Capcave** [comment]
> I don't understand why you mention ZBBridge or ZBBridgePro. These bridges work with the Zigbee network and with Zigbee devices, but we have problems with Sonoff devices connected via Wifi directly to the home router, and further through Sonoff integration with Home Assistant.Zigbee Home Automation works ok.

Ah apologies - my Wifi sonoff devices are not having any issues at all - the zigbee ones I mentioned above through the bridges suddenly started dying after the upgrade.

**Comment by mihaitaiosub** [comment]
It means that after the last updates, you have another bug that is now related to zigbee integration.

**Comment by JaCoLJcL** [comment]
After udpate to HA 2024 and Sonoff to 3.5.4 I have:

`Logger: homeassistant.loader
Source: loader.py:842
First occurred: 11:19:25 (1 occurrences)
Last logged: 11:19:25

Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 14, in <module>
    HVAC_MODE_OFF: CURRENT_HVAC_OFF,
    ^^^^^^^^^^^^^
NameError: name 'HVAC_MODE_OFF' is not defined
`
and:

`Logger: homeassistant.setup
Source: setup.py:403
First occurred: 11:19:25 (2 occurrences)
Last logged: 11:19:25

Unable to prepare setup for platform 'xiaomi_gateway3.sensor': Platform not found (Exception importing custom_components.xiaomi_gateway3.sensor).
Unable to prepare setup for platform 'xiaomi_gateway3.climate': Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).`

:(

**Comment by devezaam** [comment]
> @jeremysherriff I hadn't even seen there was an update. It seems that works now.
> 
> Thanks ;)
> 
> @devezaam have you reloaded/restarted it worked for me

It worked for me

**Comment by mihaitaiosub** [comment]
How does it work for you? With the latest updates to Sonoff integration, i.e. v3.5.4, and core 2024.1.0?

**Comment by Babe-n** [comment]
I can confirm running Sonoff LAN 3.5.4 with HA Core 2023.12.4 works without any problems. Not brave enough to try upgrade to the new HA Core 2024.1.0 and OS 11.3 again :p

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#issues

**Comment by mihaitaiosub** [comment]
An hour ago I did all three updates, Sonoff v3.5.4, HA core 2024.1.0 and OS 11.3 and I did all possible checks regarding Sonoff and Zigbee devices.So far everything is working perfectly.

**Comment by 7R0D3N** [comment]
Thanks for the v3.5.4 update, so damn quickly too. Champion.
Cheers 🍻

**Comment by bluestar888** [comment]
In order to force update ,this is what I did 
1) Go in HACS ,
2) search for Sonoff LAN 
3) choose redownload 
4) remove integration
restart HA
5) add Integration again

At some point in the journey I  read on an old thread that after redownload you need to restart HA in order to be picked up so maybe Removing the Integration was not needed. 
So it all works now. Let's see if the devices stay connected via HA Local as at some point only the cloud linked (via SmartThings or eWelink add-on)  worked .

**Comment by EmielSchonfeld** [comment]
Fixed thanks!

**Comment by jmcollin78** [comment]
I just tried with HA 2024.1.1 and SONOFF 3.5.4 and it don't work for me:
```
2024-01-06 06:45:40.062 ERROR (MainThread) [custom_components.sonoff.core.entity] Can't init device: {'name': 'Ventilateur sam', 'deviceid': '10013f49a9', 'apikey': 'f3060487-fa07-4cb1-8482-4ab52d913f5f', 'extra': {'uiid': 34, 'description': '20210709002', 'brandId': '5c4c1aee3a7d24c7100be054', 'apmac': 'd0:27:02:7e:90:a3', 'mac': 'd0:27:02:7e:90:a2', 'ui': '智能风扇灯', 'modelInfo': '607ffb615a0f126444f59385', 'model': 'PSF-BFB-GL', 'manufacturer': '深圳松诺技术有限公司', 'chipid': '008D95B2', 'staMac': '9C:9C:1F:8D:95:B2'}, 'brandName': 'SONOFF', 'brandLogo': 'https://eu-ota.coolkit.cc/logo/q62PevoglDNmwUJ9oPE7kRrpt1nL1CoA.png', 'showBrand': True, 'productModel': 'iFan04', 'tags': {'m_3f5f_jmco': 'on'}, 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '61f187a1e24f680009aedb0f', 'index': -9, 'members': [], 'roomid': '61f187a1e24f680009aedb0c'}, 'shareTo': [], 'devicekey': '05d4fc0d-bf63-4d7b-b2a2-f8d57e1170b2', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'only_device': {'ota': 'success'}, 'sledOnline': 'on', 'ssid': 'LaLiveBoxDesBoulis', 'bssid': '00:00:00:00:00:00', 'init': 1, 'fwVersion': '3.5.0', 'staMac': '9C:9C:1F:8D:95:B2', 'rssi': -83, 'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'on', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'stay', 'outlet': 2}, {'startup': 'stay', 'outlet': 3}]}, 'isSupportGroup': True, 'isSupportedOnMP': True, 'isSupportChannelSplit': False, 'deviceFeature': {}, 'device_class': 'fan'}
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/entity.py", line 86, in __init__
    self.internal_update(params)
  File "/config/custom_components/sonoff/core/entity.py", line 113, in internal_update
    self.set_state(params)
  File "/config/custom_components/sonoff/fan.py", line 58, in set_state
    self._attr_preset_modes.index(mode or SPEED_OFF)
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 338, in _getter
    return getattr(o, private_attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 338, in _getter
    return getattr(o, private_attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 338, in _getter
    return getattr(o, private_attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 977 more times]
RecursionError: maximum recursion depth exceeded
````
I tried to force the installation of integration (reload it), restart HA and I still got the error.

Am I missing something ?

**Comment by AlexxIT** [comment]
#1285

**Comment by jmcollin78** [comment]
> #1285

@AlexxIT, Sorry but I install 3.5.4 and the problem is still there. It is for me another problem and only with Fan. The others devices seems to work fine.

My device is the following:

iFan04
par SONOFF
Micrologiciel : 3.5.0
