### ISSUE TITLE
SONOFF issue on homeassistant

### ISSUE THREAD

**Issue by TlameloMojaki** [AlexxIT/SonoffLAN#1317]
After an update yesterday, my sonoff switches on homeassistant are not toggling, the status on my dashboard doesnt match the status of my lights.

**Comment by goodsale** [comment]
I have the same problems too.

The Zigbee devices linked to the sonoff hub do not respond to on off commands and the automations no longer work.

I have many Sonoff devices controlled by homeassistant and right now my house is down.

**Comment by TlameloMojaki** [comment]
@goodsale I have just rolled back to my trusted version,  version 2023.12.3 and everything is back to normal using ha terminal (" ha core update --version 2023.12.3 '')

**Comment by goodsale** [comment]
Thanks for the information.
I also went back to the previous version and everything worked again.

I therefore believe that the problem is due to the 2024.1.2 core update.

We hope that the SONOFF LAN version will be updated soon to work with the new version of Homeassistant.

**Comment by tiagonmas** [comment]
I have the same issue, on 2 different Home Assistant instances. Home Assistant status is different from eWeLink App. eWeLink is in sync with "reality", HomeAssistant is not. Several switch show in HA as being On, but they are in reality Off. When I switch them onff in HA, then turn off for a second and then back on.

**Comment by TlameloMojaki** [comment]
yup, Seems like there is an issue with SONOFF LAN on the latest version of HA. we hoping they'll release an update to remedy this issue. for now I'll stick to the HA version that is compatible with SONOFF.

**Comment by tiagonmas** [comment]
Also rolled back "using ha terminal (" ha core update --version 2023.12.3 '')". now works again.

**Comment by Quaki** [comment]
The problem is not in the version, the last time I did an update was almost a year ago. The problem is in communication with Ewelink. For now, just type reload in the Sonoff integration. There was a similar problem last year, I think in August. I don't remember exactly how the problem was solved.

Home Assistant 2023.3.4
Supervisor 2023.12.0
Operating System 9.5
Frontend 20230309.0 - latest

**Comment by tiagonmas** [comment]
I tried the reload option but it did not seem to fix for me. The rollback did!

**Comment by Quaki** [comment]
Strange, I have the same problem in the old version. The update didn't happen, I have them all disabled. For now, just enter reload in the Sonoff integration, but it will only help for a while.

Home Assistant 2023.3.4
Supervisor 2023.12.0
Operating system 9.5
Frontend 20230309.0

**Comment by goodsale** [comment]
I confirm that the reload option does not fix! Rollback only solution.

**Comment by tiefflieger666** [comment]
On my side, it stopped working (all Sonoff entities unavailable) after I upgraded Zigbee2MQTT to 1.35.1-1. Rollback to 1.35.0-1 solved the issue.

O know it's a bit strange.

**Comment by jubudu** [comment]
Same problem here after updating to 2024.1.2!
Supervisor 2023.12.0
Op-Sys: 11.4
System Restart does not help.
Reload Sonoff Integration does not help.

**Comment by ChestersGarage** [comment]
Also seeing this issue.

Got these errors:

1. 
Logger: homeassistant.loader
Source: loader.py:822
First occurred: 6:13:05 PM (1 occurrences)
Last logged: 6:13:05 PM
Unexpected exception importing component custom_components.sonoff

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/sonoff/__init__.py", line 28, in <module>
    from .core import devices as core_devices
  File "/config/custom_components/sonoff/core/devices.py", line 102, in <module>
    PULSEWIDTH = spec(XPulseWidth, param="pulseWidth", enabled=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/core/devices.py", line 88, in spec
    return type(cls.__name__, (cls,), {**cls.__dict__, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_native_step in subclass


2. 
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 6:13:05 PM (1 occurrences)
Last logged: 6:13:05 PM
Setup failed for custom integration 'sonoff': Unable to import component: Exception importing custom_components.sonoff

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/sonoff/__init__.py", line 28, in <module>
    from .core import devices as core_devices
  File "/config/custom_components/sonoff/core/devices.py", line 102, in <module>
    PULSEWIDTH = spec(XPulseWidth, param="pulseWidth", enabled=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/core/devices.py", line 88, in spec
    return type(cls.__name__, (cls,), {**cls.__dict__, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_native_step in subclass

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 830, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.sonoff



Also seeing these warnings:

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 6:13:04 PM (6 occurrences)
Last logged: 6:13:05 PM

    TEMP_CELSIUS was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
    ELECTRIC_CURRENT_AMPERE was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
    ELECTRIC_POTENTIAL_VOLT was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
    ENERGY_KILO_WATT_HOUR was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
    POWER_WATT was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues


Logger: homeassistant.components.fan
Source: helpers/deprecation.py:205
Integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 6:13:04 PM (4 occurrences)
Last logged: 6:13:04 PM

    SUPPORT_PRESET_MODE was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
    SUPPORT_SET_SPEED was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues


Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:205
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 6:13:04 PM (9 occurrences)
Last logged: 6:13:04 PM

    HVAC_MODE_HEAT_COOL was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT_COOL instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
    HVAC_MODE_OFF was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
    SUPPORT_PRESET_MODE was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
    SUPPORT_TARGET_TEMPERATURE was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
    SUPPORT_TARGET_TEMPERATURE_RANGE was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE_RANGE instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues

**Comment by ChestersGarage** [comment]
Updating to v3.5.4 has resolved the issues for me.

**Comment by vember31** [comment]
Confirming as well that this was solved by updating the integration (for me, via HACS) to the latest version and restarting home assistant. Currently on lastest version of HA core and haOS

**Comment by madchap** [comment]
The UI shows also, as a complement info the logs above:

![image](https://github.com/AlexxIT/SonoffLAN/assets/5468769/89f17f19-971d-4607-881c-8f627922e943)

![image](https://github.com/AlexxIT/SonoffLAN/assets/5468769/dab76b2d-f99b-4cfd-820a-bd8f15ba4eaa)

**Comment by pajikcz** [comment]
> The UI shows also, as a complement info the logs above:
> 
> ![image](https://private-user-images.githubusercontent.com/5468769/296536801-89f17f19-971d-4607-881c-8f627922e943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjc5OTQsIm5iZiI6MTcwNTIyNzY5NCwicGF0aCI6Ii81NDY4NzY5LzI5NjUzNjgwMS04OWYxN2YxOS05NzFkLTQ2MDctODgxYy04ZjYyNzkyMmU5NDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTAyMTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjNiNjlmY2MwY2VmNjQwOGE5NDA3ODFjYzZmMzQzM2E3Y2I0NjJmZWYwMmU3MDc3NzQ1YjdlZDgwOWU4MWQ3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bnxR1XY3YHiEWilSnfz8-TMpboWjN0lL4VxPA0djhXM)
> 
> ![image](https://private-user-images.githubusercontent.com/5468769/296536830-dab76b2d-f99b-4cfd-820a-bd8f15ba4eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjc5OTQsIm5iZiI6MTcwNTIyNzY5NCwicGF0aCI6Ii81NDY4NzY5LzI5NjUzNjgzMC1kYWI3NmIyZC1mOTliLTRjZmQtODIwYS1iZDhmMTViYTRlYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTAyMTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2FhYzI3ZGU1ZDVkNDQ5MTljMGYzNDY3YWFiYmY4ZWQ2M2YzMWRlNDJmNjFkZTZiNTc4Y2Q3NGY2YWQ3OGU4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2ZeQJLbXZc1Y3Wpje9pZGdVDauwJl-Xj83Vp0qSYezw)

yes, with latest Core: 2024.1.3 it doenst work again, i rolled back to Core: 2024.1.2 and it works for me so far

**Comment by pajikcz** [comment]
> The UI shows also, as a complement info the logs above:
> 
> ![image](https://private-user-images.githubusercontent.com/5468769/296536801-89f17f19-971d-4607-881c-8f627922e943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjk2OTMsIm5iZiI6MTcwNTIyOTM5MywicGF0aCI6Ii81NDY4NzY5LzI5NjUzNjgwMS04OWYxN2YxOS05NzFkLTQ2MDctODgxYy04ZjYyNzkyMmU5NDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTA0OTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2EyNzQ4YzlkNzRlYTJlMmFmZGRiNmNhNWRiYTYxNGQwODU1MGRlN2YzZTYzOTBiMDUwMzM1ZDNiMDQ0MzIzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZHfwP-dD56mPefIF2LjhLQbMo_b9c8_Yl8pNLvt--Rs)
> 
> ![image](https://private-user-images.githubusercontent.com/5468769/296536830-dab76b2d-f99b-4cfd-820a-bd8f15ba4eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjk2OTMsIm5iZiI6MTcwNTIyOTM5MywicGF0aCI6Ii81NDY4NzY5LzI5NjUzNjgzMC1kYWI3NmIyZC1mOTliLTRjZmQtODIwYS1iZDhmMTViYTRlYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTA0OTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjk2YzZhN2YwNTJjZWQ4ZmE2ZTZhNjZhMWMyNTA3NmQzOGVlZDQ5OWYzMDZhNzJkMjA0NDRlZDIzY2I1Njk0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lMP84lTRRuncEkBgGPVfED_w9nysqJX7i3epoX7uRK4)

try install SONOFF LAN integration via HACS plugin, not only via Setting/Devices and Button bellow

**Comment by madchap** [comment]
I just restored a 2 days ago backup, was still on 2023.12.4.. of course, lost 2 days of energy summary :-/

**Comment by madchap** [comment]
But yes indeed.. just saw the post above too late, I rarely check HACS... I restored the most recent backup of HA to 2014.1.3 and updated Sonoff to 3.5.4, and this works.

**Comment by vrabi-cv** [comment]
> The UI shows also, as a complement info the logs above:
> 
> ![image](https://private-user-images.githubusercontent.com/5468769/296536801-89f17f19-971d-4607-881c-8f627922e943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNTU1MjIsIm5iZiI6MTcwNTI1NTIyMiwicGF0aCI6Ii81NDY4NzY5LzI5NjUzNjgwMS04OWYxN2YxOS05NzFkLTQ2MDctODgxYy04ZjYyNzkyMmU5NDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTgwMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAyZTdlZDE4ODNlYzBiMmM5OTVmNTgyNjExYjMxNjkzOThhMzUxMjMxMmQ4NzlmYzExNjNkYTFlM2NhNTM5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DT_Us7zfTy5nhTtQK99YQM8XI4FNWk6ZLLuDcb9qK4U)
> 
> ![image](https://private-user-images.githubusercontent.com/5468769/296536830-dab76b2d-f99b-4cfd-820a-bd8f15ba4eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNTU1MjIsIm5iZiI6MTcwNTI1NTIyMiwicGF0aCI6Ii81NDY4NzY5LzI5NjUzNjgzMC1kYWI3NmIyZC1mOTliLTRjZmQtODIwYS1iZDhmMTViYTRlYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTgwMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2JhMjI4NDg3Y2FjMDFkMTMzODFiMWMwMDQ0YjE0YjE4NTM5ZjdhYmM0NWEyYjg0OWY2Y2Q1ZWYzNWI2MjViMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ovfykykj9bj61k5_NamV-cowpdxY1Ghkyu82BYg_zNs)

Got exactly same issue...disabled sonoff integration, removed the integration, restarted HA (recheck whether sonoff is deleted), install the integration from HACS, restarted HA.....renabled the integration (was shown only in list of disabled integrations) and .... voilá , all devices working and appears same as before.
Do not worry and give it a try to remove and install again:)

**Comment by goodsale** [comment]
Solved with v3.5.4!

Thanks!

**Comment by xmicky** [comment]
> After updating to v3.5.4 because of this issue (hass 2024.1.3) I get the following error:
> 
> ```
> Logger: homeassistant.setup
> Source: setup.py:251
> First occurred: 9:18:33 AM (1 occurrences)
> Last logged: 9:18:33 AM
> 
> Setup failed for custom integration 'sonoff': Unable to import component: No module named 'custom_components.'
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
>     component = integration.get_component()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
>     ComponentProtocol, importlib.import_module(self.pkg_path)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'custom_components.'
> ```
> 
> I just extracted the `custom_components` directory from the release package https://github.com/AlexxIT/SonoffLAN/archive/refs/tags/v3.5.4.tar.gz into `/usr/share/hassio/homeassistant/custom_components`:
> 
> ```
> usr@ubuntu:/usr/share/hassio/homeassistant/custom_components$ tree
> .
> └── sonoff
>     ├── binary_sensor.py
>     ├── button.py
>     ├── climate.py
>     ├── config_flow.py
>     ├── core
>     │   ├── const.py
>     │   ├── devices.py
>     │   ├── entity.py
>     │   └── ewelink
>     │       ├── base.py
>     │       ├── camera.py
>     │       ├── cloud.py
>     │       ├── __init__.py
>     │       └── local.py
>     ├── cover.py
>     ├── diagnostics.py
>     ├── fan.py
>     ├── __init__.py
>     ├── light.py
>     ├── manifest.json
>     ├── number.py
>     ├── remote.py
>     ├── sensor.py
>     ├── services.yaml
>     ├── switch.py
>     ├── system_health.py
>     └── translations
>         ├── ar.json
>         ├── ee.json
>         ├── en.json
>         ├── es.json
>         ├── fr-ca.json
>         ├── hu.json
>         ├── id.json
>         ├── pl.json
>         ├── pt-BR.json
>         ├── ru.json
>         ├── sk.json
>         ├── tr.json
>         ├── uk.json
>         └── ur.json
> 
> 4 directories, 38 files
> ```

I had the same message when updating to ha core 2024.1.3
The only thing that has worked for me to solve this issue  is to rollback to ha core 2023.12.3

**Comment by xmicky** [comment]
I had the same problems and I’ve tried combinations of ha core and sonoff lan versions .
I found that there are two best workaround combinations
Ha core 2023.12.3 and sonoff lan 3.5.4 (I didn’t try core 2023.12.4 and 2024.x.x didn’t work)
Ha core 2024.1.3 and sonoff lan 3.5.3. (These core versions that I tried also worked 2024.1.1, 2024.1.2)

**Comment by feiticeir0** [comment]
Thank you all for the comments. Latest HA wasn't working. I downgraded HA:
```
Core 2023.12.3
Supervisor 2023.12.1
Operating System 11.4
Frontend 20231208.2
```

- I had removed the integration, so I had to add it again and now everything is working. I finally have notifications for my garage doors again ! 
-

**Comment by feiticeir0** [comment]
> Thank you all for the comments. Latest HA wasn't working. I downgraded HA:
> 
> ```
> Core 2023.12.3
> Supervisor 2023.12.1
> Operating System 11.4
> Frontend 20231208.2
> SONOFF LAN v3.5.2
> ```
> 
>     * I had removed the integration, so I had to add it again and now everything is working. I finally have notifications for my garage doors again !

I really didn't check HACS for an update. After updating SONOFF integration to the latest version and HA to the latest version, everything is working.

```
Sonoff LAN v3.5.4

Core 2024.1.4
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

```

Thank you

**Comment by FakeTruth** [comment]
Ah, I had renamed my old SONOFF custom_component to `.sonoff_BAK` which was apparently interfering. I do believe this worked without problems before.
Anyway, I removed the `.sonoff_BAK` directory and only kept the must current version `Sonoff LAN v3.5.4` installed as it should and now everything is working 🥳 So for me this was an error on my end, nothing to do with the SONOFF component.

**Comment by heyhewmike** [comment]
I am having the same issue. Updated Sonoff Integration & HAOS
Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Sonoff Integration 3.5.4

I am attempting the rollback to ha core 2023.12.3

**Comment by Mike-kk-de** [comment]
beginner question:
How can i update sonoff integration?

**Comment by heyhewmike** [comment]
> beginner question:
> How can i update sonoff integration?
> 

I have not heard of an update to the integration. Normally there would be an alert for an update similar to other updates performed in Home Assistant.

I found rolling Home Assistant back following [this comment](https://github.com/AlexxIT/SonoffLAN/issues/1317#issuecomment-1886962979). You can do this through a ssh/terminal add-on/integration or from a keyboard & monitor

**Comment by heyhewmike** [comment]
Hello Everyone,

I rolled HA Core back about 2 weeks ago. And my devices started going offline again.

Does anyone have any other fixes?

**Comment by mike-kk-dd** [comment]
installing the SonOff 3.5.4 solved my problem.
Now HA is up to Date with working sonoff

I only had to reconfigure the tuya addon

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#issues
