### ISSUE TITLE
Led driver Became unavailable repeatedly

### ISSUE THREAD

**Issue by magilla13** [AlexxIT/SonoffLAN#1460]
Sonoff L2 led driver attached to ewelink via wifi became unavailable after few seconds and became available again after few seconds.
It repeats continously.
In ewelink app the device working and available properly. (Previously it was fine, but I see this issue sonce I upgraded from 2024.6.x to 7.2 -7.3.7.4

Additionally when it happens for few minutes my server restarts unexpectedly.
When I disable the this led driver entity I don't see any issue with the system.

**Comment by adamnagybig** [comment]
Same is for me and worse. All my switched which have power meters in it become unavailable and after 3 seconds available. All my wifi door sensors behave the same.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#issues

**Comment by magilla13** [comment]
Thanks Alex. Can you please highlight the relevant section to solve my issue? (I went through on it earlier but didn't find...)

Thanks

**Comment by AlexxIT** [comment]
This link with anchor to **Issues** section. No sense to post any problems without diagnostics.

**Comment by magilla13** [comment]
Here is the diag file.
[config_entry-sonoff-6dc973a342efe5cabc38657981f06212.json](https://github.com/user-attachments/files/16487986/config_entry-sonoff-6dc973a342efe5cabc38657981f06212.json)

**Comment by elektrik216** [comment]
I have same issue. It become last week. For couple days worked fine and then again connecting and disconnecting every 4-5 s for week and continue today. Only the devises which are conected in local network are work as they should.

**Comment by adamnagybig** [comment]
> I have same issue. It become last week. For couple days worked fine and then again connecting and disconnecting every 4-5 s for week and continue today. Only the devises which are conected in local network are work as they should.

For me it is exactly the same, even now i have the issue.

**Comment by adamnagybig** [comment]
@AlexxIT 

My diagnostic is also attached.

[config_entry-sonoff-19ebd1cad49c547e7c754d9226a6e473.json](https://github.com/user-attachments/files/16740803/config_entry-sonoff-19ebd1cad49c547e7c754d9226a6e473.json)

**Comment by AlexxIT** [comment]
```
Traceback (most recent call last):
  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 598, in _process_ws_msg
    self._set_response(data[\"sequence\"], data[\"error\"])
                       ~~~~^^^^^^^^^^^^
KeyError: 'sequence'
```

**Comment by AlexxIT** [comment]
Fixed in master version

**Comment by magilla13** [comment]
> Fixed in master version

Thanks @AlexxIT for your reply and effort.
I'm not a tech guy. Can you please help me "Fixed in master version" means an update will arrive to HA later on or I / we need to update something in the existing system?

Thanks

**Comment by AlexxIT** [comment]
If you don't wont to wait next release - you should install master version manually

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.0

**Comment by magilla13** [comment]
Hi @AlexxIT ,

Thanks to release the new revision. I immediately updated my system and enabled the devices but still get the same behavior. Please see attached the diag file.
[config_entry-sonoff-6dc973a342efe5cabc38657981f06212.json](https://github.com/user-attachments/files/16921206/config_entry-sonoff-6dc973a342efe5cabc38657981f06212.json)

Can you please check what could be the problem?
Thanks
Attila

**Comment by AlexxIT** [comment]
@magilla13 

> You logged in from another place

https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#configuration

**Comment by magilla13** [comment]
@AlexxIT  Awesome. Thanks :)
Now it is working :)

**Comment by adamnagybig** [comment]
@AlexxIT Many Many Thanks.

Everythings works perfectly.

**Comment by adamnagybig** [comment]
It worked fine, there was a core update.

Now the situation is almoust the same. Sometimes it is stable for more then
5 minutes and then they go unavailable for 10 seconds, sometimes it gets
crazy and switch between available and unavailable every 10 seconds.
