### ISSUE TITLE
Sonoff S40 smart plug doesn't update powermeter number

### ISSUE THREAD

**Issue by kingwap99** [AlexxIT/SonoffLAN#739]
https://itead.cc/product/sonoff-iplug-series-wi-fi-smart-plug-s40-s40-lite/

new model Sonoff S40 the successor of Sonoff S31 already be announced,

after tested it, I found that 
1. the official component from ewelink not support S40.
2. SonoffLAN (cloud mode) can switch on/off it, but the powermeter number can be updated only when the ewelink app is running.

**Comment by AlexxIT** [comment]
Please enable debug mode and show logs

**Comment by kingwap99** [comment]
> Please enable debug mode and show logs

already sent to sonofflan@gmail.com
thanks a lot

**Comment by AlexxIT** [comment]
Check new beta-version:
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.0rc1

**Comment by kingwap99** [comment]
just tried v3.0rc1 with cloud mode
sonoff s31 can work well, but S40 still got the same issue.
the power meter number can be updated, only when the e-welink app was opened.

**Comment by AlexxIT** [comment]
I hope S40 problem fixed in latest master-version.

**Comment by kingwap99** [comment]
> Please enable debug mode and show logs

already enabled it, but seems something wrong, the debug message didn't show up.
![螢幕擷取畫面 2022-04-24 144030](https://user-images.githubusercontent.com/33337987/164960277-00cd8c2b-6033-4481-9085-cfb86dbc992c.jpg)

**Comment by AlexxIT** [comment]
Do you search debug in right place?

**Comment by kingwap99** [comment]
> Do you search debug in right place?

would be right, because when I switch back to v2.4.7, it shows up on the notification window, but 3.x not
![螢幕擷取畫面 2022-04-24 192934](https://user-images.githubusercontent.com/33337987/164974750-f3f9acbb-e8a0-4d15-96eb-0fd21c5a44f0.jpg)
![螢幕擷取畫面 2022-04-24 193910](https://user-images.githubusercontent.com/33337987/164974751-22491dc2-2064-44e9-9940-a3a718b82249.jpg)

**Comment by AlexxIT** [comment]
Read carefully image where you enable Debug check box.

**Comment by kingwap99** [comment]
> Read carefully image where you enable Debug check box.

hahaha
Just sent to sonofflan@*

**Comment by AlexxIT** [comment]
Are you sure you have installed latest master version? I can't see this command with S40 device in your logs
https://github.com/AlexxIT/SonoffLAN/blob/54d7efe7ca12299c29f0782b6a650761cd7b9470/custom_components/sonoff/core/devices.py#L171

**Comment by kingwap99** [comment]
> Are you sure you have installed latest master version? I can't see this command with S40 device in your logs
> 

yes, I have the question also, 
the device id of my S40 is  100158603f 

![螢幕擷取畫面 2022-04-25 025803](https://user-images.githubusercontent.com/33337987/164992126-7aac5cd4-cbd5-4122-a11a-8f8ba0d41e4a.jpg)

**Comment by AlexxIT** [comment]
Your pow devices has this line in logs:
```
2022-04-24 21:37:36 [D] 1000fefe42 => Cloud4 | {'uiActive': 7200} | 1650807456950
```
Your S40 - don't

**Comment by AlexxIT** [comment]
You can open power screen for S40 in ewelink mobile app and collect component logs for this moment

**Comment by AlexxIT** [comment]
Or you can share this device to my account. I don't get it last time

**Comment by kingwap99** [comment]
> Or you can share this device to my account. I don't get it last time

Is this correct account ?

![IMG_20220425_120257](https://user-images.githubusercontent.com/33337987/165019306-078ec2f8-f0ff-4086-8e23-e9f3eb98e0d5.jpg)

**Comment by kingwap99** [comment]
> Or you can share this device to my account. I don't get it last time

Please just try this account as below:
kingwap.tw@gmail.com / Sonofflan

I plugged it on my ups

**Comment by AlexxIT** [comment]
Fixed in latest master

**Comment by AlexxIT** [comment]
Can you show how often pow devices send power data in **only local mode** on integration v3.0?
I know S40 works only via cloud but you have many pow devices

**Comment by kingwap99** [comment]
> Can you show how often pow devices send power data in **only local mode** on integration v3.0? I know S40 works only via cloud but you have many pow devices

very fast, would be only 1sec
and already installed one S31 device on that testing account
you can try it by your own, if you like
{"deviceid":"1000fefd5d","apikey":"3bc9c0c5-0ad9-40fc-93ee-5ea589a3db4f","accept":"post","chipid":"0007EF40"}

**Comment by AlexxIT** [comment]
Ok. Thanks. I can't test your device with LAN protocol...

**Comment by roberthamilton-pm** [comment]
I'm still seeing this issue with S40 devices — unless I have the mobile app open, HA doesn't update the history for the power sensor. I can share logs if it helps.
